---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-wrk-deployment
  labels:
    app: app-prod-wrk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-prod-wrk
  template:
    metadata:
      labels:
        app: app-prod-wrk
    spec:
      containers:
        - name: app-prod-wrk
          imagePullPolicy: Always
          image: nikhilsharma710/app-wrk:0.1
          command: ['python3', 'worker.py']
          env:
          - name: REDIS_IP
            value: 10.96.6.150
          ports:
          - name: http
            containerPort: 5000
