---
apiVersion: v1
kind: Service
metadata:
  name: app-db-service
spec:
  type: ClusterIP
  selector:
    app: app-prod-db
  ports:
  - name: app-prod-db
    port: 6379
    targetPort: 6379
