---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-wrk-deployment
  labels:
    username: app
    env: prod
    app: app-prod-wrk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-prod-wrk
  template:
    metadata:
      labels:
        app: app-prod-wrk
    spec:
      containers:
        - name: app-prod-wrk
          imagePullPolicy: Always
          image: nikhilsharma710/hw05:1.0  #change image
          command: ['python3', 'worker.py']
          ports:
          - name: http
            containerPort: 5000
          env:
          - name: REDIS_IP  #change
            value: 10.96.56.194 
