---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-deployment
  labels:
    env: prod
    app: app-prod-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-prod-api
  template:
    metadata:
      labels:
        app: app-prod-api
    spec:
      containers:
        - name: app-prod-api
          imagePullPolicy: Always
          image: nikhilsharma710/app-api:0.1
          command: ['python3', 'flask_api.py']
          env:
          - name: REDIS_IP
            value: 10.96.6.150
          ports:
          - name: http
            containerPort: 5000
