---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  labels:
    username: app
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
