---
version: '3'
services:
    redis:
        image: redis:latest
        container_name: nikhilsharma710-app-db
        ports:
            - 6429:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
